- file:
    path: "{{ item.path }}"
    state: "{{ item.type }}"
    mode: "{{ item.permissions }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: yes
  with_items: "{{ filesystem }}"
