---
- name: Ensure python is installed
  hosts: all
  user: root
  gather_facts: False
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False

- name: Install software on server
  hosts: all
  become: True
  roles:
    - { role: apt,        tags: ["apt"] }
    - { role: filesystem, tags: ["filesystem", "caddy"] }
    - { role: nodejs,     tags: ["nodejs"] }
    - { role: caddy,      tags: ["caddy"] }
