---
- name: Ensure python is installed
  hosts: all
  user: root
  gather_facts: False
  tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal python-pip)

- name: Set up users on new server
  hosts: all
  user: root
  roles:
    - { role: users, tags: ["users"] }
